In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/california-housing-prices/housing.csv
/kaggle/input/heart-disease-dataset/heart-disease.csv


In [2]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 


In [3]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("camnugent/california-housing-prices")

# print("Path to dataset files:", path)



In [4]:
housing = pd.read_csv("/kaggle/input/california-housing-prices/housing.csv")

In [5]:
housing.drop("ocean_proximity" , inplace=True , axis = 1)
housing = housing.dropna(subset="total_bedrooms")


In [6]:
np.random.seed(42)
x = housing.drop("median_house_value" , axis = 1)
y = housing["median_house_value"]

housing.isna().sum()




longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
dtype: int64

In [7]:
from sklearn.model_selection import train_test_split 
x_train , x_test , y_train , y_test = train_test_split(x, y , test_size= 0.2)

In [8]:
from sklearn.linear_model import Ridge

model = Ridge()
model.fit(x_train , y_train)



Ridge()

In [9]:
model.score(x_train , y_train)

0.6360185691316951

In [10]:
model.score(x_test , y_test)

0.6400858817984223

# Lasso 

In [11]:
from sklearn.linear_model import Lasso 

model1 = Lasso()

model1.fit(x_train , y_train)

Lasso()

In [12]:
model1.score(x_train , y_train)

0.636018572207647

In [13]:
model1.score(x_test , y_test)

0.6400862985932623

## Ensemble Model :- Its a combination of smaller models to try and make better prediction than just a single model 

In [14]:
from sklearn.ensemble import RandomForestRegressor 

model1 = RandomForestRegressor()

model1.fit(x_train , y_train)

RandomForestRegressor()

In [15]:
model1.score(x_train , y_train)

0.9748097758655744

In [16]:
model1.score(x_test , y_test)

0.8214550319185272

### Prediction for a Regression Model 

In [17]:
y_preds = model1.predict(x_test)
np.array(y_preds[:5])

array([214237.01, 155280.  , 192216.  , 135481.  , 164132.  ])

In [18]:
np.array(y_test[:5])

array([245800., 137900., 218200., 220800., 170500.])

In [19]:
# Average difference between the predicted value and the true value 
# The output which is 32088.217729385862 tells on average this is the value that is 
# different from the true value just found the average of (y_preds - y_test)
from sklearn.metrics import mean_absolute_error 

mean_absolute_error(y_test , y_preds)

32088.217729385862

In [20]:
y_prediction = model1.predict(x_test)
y_prediction 

array([214237.01, 155280.  , 192216.  , ...,  90607.  , 108531.  ,
       111421.  ])

### Evaluating a Machine learning Model 

Three ways to evaluate scikit-learn models/estimators 

1. Estimator's built in `score` method 
2. The `scoring` parameter 
3. Problem specific metric functions 


## Regression Model Evaluation Metrics 

Types are :
1. R^2 (R - squared ) or coefficient of determination
2. Mean absolute Error (MAE)
3. Mean squared error (MSE)

## R^2:

what R^2 does is compares your model prediction to the mean of the targets. values can range from negative infinity (a very poor model) to 1 . For example all your model does is predict the mean of the targets , its R^2 value would be 0.
If your model perfectly predicts a range of numbers its R^2 value would be 1.


In [21]:
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor()

model.fit(x_train , y_train)

RandomForestRegressor()

In [22]:
from sklearn.metrics import r2_score 
r2_score(y_true = y_test ,y_pred = y_prediction)

0.8214550319185272

In [23]:
# Model performs worst everything is wrong 
r2_score(y_true = y_test , y_pred = np.full(len(y_test) , y_test.mean()))

0.0

In [24]:
# Model performs perfectly 
r2_score(y_true = y_test , y_pred = y_test)

1.0

**Mean Absolute Error (MAE):**

MAE is the average of the absolute differneces between predictions and actual values.

It gives you an idea about how wrong your model predictions are 


In [25]:
from sklearn.metrics import mean_absolute_error

y_prediction = model.predict(x_test)

mean_absolute_error(y_test , y_prediction)

31997.10869341815

In [26]:
df = pd.DataFrame(data = {"Actual values" : y_test ,
                          "Predicted values" : y_prediction,
                         })

df["differences"] = abs(df["Actual values"] - df["Predicted values"])

df["squared_differences"] = np.square(df["differences"])

df.head(10)



Actual values  Predicted values  differences  squared_differences
14416       245800.0         213389.01     32410.99         1.050472e+09
16383       137900.0         154565.00     16665.00         2.777222e+08
7731        218200.0         189501.00     28699.00         8.236326e+08
1410        220800.0         140385.00     80415.00         6.466572e+09
1335        170500.0         164394.00      6106.00         3.728324e+07
16260        75000.0          73953.00      1047.00         1.096209e+06
18011       269400.0         281999.02     12599.02         1.587353e+08
10086       228900.0         209420.00     19480.00         3.794704e+08
18294       500001.0         459793.41     40207.59         1.616650e+09
18733        80800.0          72562.00      8238.00         6.786464e+07

In [27]:
#  This is what mean_absolute_error is calculating 
print(df["differences"].mean())
print(np.mean(np.absolute(y_test - y_prediction)))

# This is what mean_squared_error is calculating 
print(np.mean(df["squared_differences"]))

31997.10869341815
31997.10869341815
2453355545.218117


**Mean squared error**

In [28]:
from sklearn.metrics import mean_squared_error 
mean_squared_error(y_test , y_prediction)

2453355545.218117

In [29]:
y_preds = model.predict(x_test)
y_preds

array([213389.01, 154565.  , 189501.  , ...,  85408.  , 109704.  ,
       115236.  ])

### using the `scoring` parameter 

In [30]:
from sklearn.ensemble import RandomForestRegressor 
model = RandomForestRegressor()

x = housing.drop("median_house_value" , axis = 1)
y = housing["median_house_value"]

from sklearn.model_selection import train_test_split 

x_train , x_test , y_train , y_test = train_test_split(x, y , test_size = 0.2)

model.fit(x_train , y_train)

RandomForestRegressor()

**cross_value_score**

In [31]:
from sklearn.model_selection import cross_val_score

np.random.seed(42)

cv_score = cross_val_score(model , x , y , cv = 5 , scoring = None) # if scoring = none the estimator's default scoring metrics is used (like accuracy for classification estimator)
cv_score

array([0.42354413, 0.62526004, 0.69972816, 0.56725585, 0.61283367])

In [32]:
print(f"The cross-validated accuracy is {np.mean(cv_score)*100:.2f}%")

The cross-validated accuracy is 58.57%


In [33]:
np.random.seed(42)
cv_accuracy = cross_val_score(model , x , y , cv = 5 , scoring="neg_mean_absolute_error")
cv_accuracy 

array([-57218.43318082, -50061.92359188, -46957.56604111, -49156.50649046,
       -52151.63154674])

In [34]:
np.random.seed(42)
cv_r2score = cross_val_score(model , x , y , cv = 3 , scoring = "neg_mean_squared_error")
cv_r2score

array([-6.33835948e+09, -3.73061402e+09, -6.61463356e+09])

## Improving our model 

first prediction = baseline prediction 
first model = baseline model 

From a data perspective :
* could we collect more data (generally the more data , the better)
* could we improve our data

From a model perspective :
* is there a better model we could use ?
* could we improve our current model

Hyperparameters vs parameters 
* parameters : model find these patterns in the data
* Hyperparameters : settings on a model you can adjust to (potentially) improve its ability to find patterns.

Three ways to adjust hyperparameters:
1. By hand
2. Randomly with RandomSearchCV
3. Exhaustively with GridSearchCV

In [35]:
model.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'criterion': 'squared_error',
 'max_depth': None,
 'max_features': 1.0,
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [36]:
heart_disease = pd.read_csv("/kaggle/input/heart-disease-dataset/heart-disease.csv")

In [37]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()

x = heart_disease.drop("target" , axis = 1)
y = heart_disease["target"]

from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x , y , test_size = 0.2)

model.fit(x_train , y_train)

RandomForestClassifier()

In [38]:
y_preds = model.predict(x_test)
y_preds

array([1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1])

**Training set** is like a course material which we use to learn something 

**Validation set** is like a practice test 

**Test SET** is the final exam

### Tuning Hyperparameters by hand 

lets take 3 sets training , validation and test 

In [39]:
model.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

### We are going to try and adjust :
* `Max_depth`
* `max_features`
* `min_sample_leaf`
* `min_sample_split`
* `n_estimators`


In [40]:
from sklearn.metrics import accuracy_score , precision_score , recall_score , f1_score

def evaluate_preds(y_test , y_preds):
    """
    performs evaluation comparision on y_true labels versus y_prediction labels on 
    a classification model .
    """
    accuracy = accuracy_score(y_test , y_preds)
    precision = precision_score(y_test , y_preds)
    recall = recall_score(y_test , y_preds)
    f1 = f1_score(y_test , y_preds)

    metric_dict = {
        "Accuracy": round(accuracy , 2) , 
        "precision": round(precision , 2) , 
        "recall" : round(recall , 2) , 
        "f1" : round(f1 , 2) 
    }

    print(f"Acc: {accuracy * 100 :.2f}%")
    print(f"Precision: {precision * 100 :.2f}%")
    print(f"recall: {recall * 100 :.2f}%")
    print(f"f1: {f1 * 100 :.2f}%")

    return metric_dict




In [41]:
from sklearn.ensemble import RandomForestClassifier 


np.random.seed(42)

# shuffle the data 
heart_disease_shuffled = heart_disease.sample(frac = 1) #frac = 1 means 100% of the data 

# split into x and y 

x = heart_disease_shuffled.drop("target" , axis = 1)
y = heart_disease_shuffled["target"]
# split the data into train , validation and test (70-15-15)%

train_split = round(0.7*(len(heart_disease_shuffled)))
validation_split = round(train_split + .15 * len(heart_disease_shuffled))

x_train , y_train = x[:train_split] , y[:train_split]
x_valid , y_valid = x[train_split:validation_split] , y[train_split: validation_split]
x_test , y_test = x[validation_split:] , y[validation_split:]

model = RandomForestClassifier(n_estimators = 10)
model.fit(x_train , y_train)

y_preds = model.predict(x_valid)

# Evaluate the classifier on validation set 
baseline_metrics = evaluate_preds(y_valid , y_preds)
baseline_metrics 

Acc: 80.00%
Precision: 76.67%
recall: 92.00%
f1: 83.64%


{'Accuracy': 0.8, 'precision': 0.77, 'recall': 0.92, 'f1': 0.84}

In [42]:
np.random.seed(42)
# create a second classifier for the same data but with different hyperparameters 

model2 = RandomForestClassifier(n_estimators = 100) #by default n_estimator is 100

model2.fit(x_train , y_train)

# make predictions 
y_preds_2 = model2.predict(x_valid)

# evaluate the classifier on validation set 

model_2_metrics = evaluate_preds(y_valid , y_preds_2)
model_2_metrics

Acc: 82.22%
Precision: 84.00%
recall: 84.00%
f1: 84.00%


{'Accuracy': 0.82, 'precision': 0.84, 'recall': 0.84, 'f1': 0.84}

In [43]:
# Now we will change max-depth from none to 10 by making model3

model3 = RandomForestClassifier(max_depth = 10)

model3.fit(x_train , y_train)

y_preds_3 = model3.predict(x_valid)

model3_metrics = evaluate_preds(y_valid , y_preds_3)

model3_metrics



Acc: 82.22%
Precision: 81.48%
recall: 88.00%
f1: 84.62%


{'Accuracy': 0.82, 'precision': 0.81, 'recall': 0.88, 'f1': 0.85}